# -*- coding: utf-8 -*-
"""Manajemen Portofolio Saham Menggunakan Proximal Policy Optimization (PPO).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JcGN5dUeJE8I9vIx0E4pmNhyBteN5TnU
"""

pip install stable-baselines3 gym pandas-datareader numpy pandas matplotlib

!echo "# Manajemen-Portofolio-Saham-Menggunakan-Proximal-Policy-Optimization-" >> README.md
!git init
!git config --global user.email "tobyelfest@gmail.com"
!git config --global user.name "tobyelfest"
!git add README.md
!git commit -m "first commit"
!git branch -M main
!git remote add origin https://github.com/tobyelfest/Manajemen-Portofolio-Saham-Menggunakan-Proximal-Policy-Optimization-.git
!git push -u origin main

!pip install mlflow pyngrok -q

pip install "shimmy>=2.0"

!pip install dvc dvc-gdrive -q
!git init
!dvc init -f
!dvc config cache.type copy

import pandas as pd
import numpy as np
import gym
from gym import spaces
from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env
import matplotlib.pyplot as plt
import os
import mlflow

file_path = '/all_stocks_5yr.csv'
df = pd.read_csv(file_path)

# Convert date to datetime objects
df['date'] = pd.to_datetime(df['date'])

# Select a single stock (e.g., AAPL) for simplicity
stock_df = df[df['Name'] == 'AAPL'].sort_values('date').reset_index(drop=True)

# Display the first few rows of the selected stock data
print("Selected Stock Data (AAPL):")
display(stock_df.head())

# Extract closing prices for the environment
prices = stock_df['close'].values

plt.figure(figsize=(14, 7))
plt.plot(stock_df['date'], prices)
plt.title('AAPL Stock Price Over 5 Years')
plt.xlabel('Date')
plt.ylabel('Close Price ($)')
plt.grid(True)
plt.show()

class StockTradingEnv(gym.Env):
    metadata = {'render_modes': ['human'], 'render_fps': 30}

    def __init__(self, prices, initial_balance=10000, lookback_window_size=10):
        super(StockTradingEnv, self).__init__()
        self.prices = prices
        self.initial_balance = initial_balance
        self.lookback_window_size = lookback_window_size
        self.current_step = lookback_window_size

        # Actions: -1 = sell all, 1 = buy all, 0 = hold
        self.action_space = spaces.Box(low=-1, high=1, shape=(1,), dtype=np.float32)

        # Observation Space
        self.observation_space = spaces.Box(
            low=0,
            high=np.inf,
            shape=(self.lookback_window_size + 2,),
            dtype=np.float32
        )

        self.fig = None # Inisialisasi untuk render
        self.reset()

    def _get_obs(self):
        """Get the observation (state) for the agent"""
        obs = np.array([
            *self.prices[self.current_step - self.lookback_window_size : self.current_step],
            self.balance,
            self.shares_held
        ], dtype=np.float32)
        return obs

    def _get_info(self):
        """Get additional information for debugging/logging"""
        return {
            'current_price': self.prices[self.current_step],
            'balance': self.balance,
            'shares_held': self.shares_held,
            'net_worth': self.net_worth
        }

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.balance = self.initial_balance
        self.shares_held = 0
        self.net_worth = self.initial_balance
        self.current_step = self.lookback_window_size
        self.history = []

        observation = self._get_obs()
        info = self._get_info()
        return observation, info

    def step(self, action):
        current_price = self.prices[self.current_step]
        action_val = action[0]

        prev_net_worth = self.net_worth

        # Eksekusi Aksi
        shares_traded = 0
        if action_val > 0: # Buy
            shares_to_buy = int((self.balance * action_val) / current_price)
            if shares_to_buy > 0:
                self.balance -= shares_to_buy * current_price
                self.shares_held += shares_to_buy
                shares_traded = shares_to_buy
        elif action_val < 0: # Sell
            shares_to_sell = int(self.shares_held * abs(action_val))
            if shares_to_sell > 0:
                self.balance += shares_to_sell * current_price
                self.shares_held -= shares_to_sell
                shares_traded = -shares_to_sell

        # Update Net Worth
        self.net_worth = self.balance + self.shares_held * current_price
        reward = self.net_worth - prev_net_worth

        # Simpan History
        self.history.append({
            'step': self.current_step,
            'price': current_price,
            'action': action_val,
            'shares_after': self.shares_held,
            'balance': self.balance,
            'net_worth_after': self.net_worth,
            'net_worth_before': prev_net_worth,
            'shares_traded': shares_traded
        })

        self.current_step += 1
        done = self.current_step >= len(self.prices) - 1 or self.net_worth <= self.initial_balance / 2

        return self._get_obs(), reward, done, False, self._get_info()

    def render(self, mode='human'):
        if mode == 'human':
            if self.fig is None:
                self.fig, self.ax = plt.subplots(figsize=(12, 6))
                self.ax2 = self.ax.twinx()

            # (Fungsi render real-time ini opsional jika Anda sudah punya render_all_history)
            plt.clf()
            df = pd.DataFrame(self.history)
            if not df.empty:
                plt.plot(df['price'])
                plt.title("Current Simulation Progress")
                plt.pause(0.001)

    def close(self):
        if self.fig:
            plt.close(self.fig)
            self.fig = None

    def render_all_history(self, title="Trading Performance Summary"):
        if not self.history:
            print("No history to render.")
            return

        df = pd.DataFrame(self.history)
        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True, gridspec_kw={'height_ratios': [2, 1]})
        fig.suptitle(title, fontsize=16)

        # Plot Harga & Net Worth
        ax1.plot(df['step'], df['price'], label='Stock Price', color='black', alpha=0.3, linestyle='--')
        ax1.plot(df['step'], df['net_worth_after'], label='Net Worth', color='green', linewidth=2)

        buys = df[df['shares_traded'] > 0]
        sells = df[df['shares_traded'] < 0]
        ax1.scatter(buys['step'], buys['price'], marker='^', color='lime', label='Buy Signal', s=80, zorder=5)
        ax1.scatter(sells['step'], sells['price'], marker='v', color='red', label='Sell Signal', s=80, zorder=5)

        ax1.set_ylabel('Value ($)')
        ax1.legend(loc='upper left')
        ax1.grid(True, alpha=0.3)

        # Plot Posisi Saham
        ax2.plot(df['step'], df['shares_after'], label='Shares Held', color='purple')
        ax2.fill_between(df['step'], df['shares_after'], color='purple', alpha=0.1)
        ax2.set_ylabel('Shares')
        ax2.set_xlabel('Time Step')
        ax2.grid(True, alpha=0.3)

        # Statistik
        start_nw = df['net_worth_before'].iloc[0]
        end_nw = df['net_worth_after'].iloc[-1]
        roi = ((end_nw - start_nw) / start_nw) * 100
        stats = f'Initial Balance: ${start_nw:.2f}\nFinal Net Worth: ${end_nw:.2f}\nROI: {roi:.2f}%'
        ax1.text(0.02, 0.95, stats, transform=ax1.transAxes, verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

        plt.tight_layout()
        plt.show()

if __name__ == "__main__":
    N = 500
    t = np.linspace(0, 4 * np.pi, N)
    base_prices = 100 + 30 * np.sin(t) + np.random.normal(0, 2, N)
    base_prices = np.maximum(base_prices, 10)

    env = StockTradingEnv(prices=base_prices, initial_balance=10000, lookback_window_size=15)
    obs, info = env.reset()

    print("Memulai simulasi dengan Random Actions...")
    done = False
    while not done:
        action = env.action_space.sample()
        obs, reward, done, truncated, info = env.step(action)
        if truncated: break

    print("Simulasi selesai.")
    env.render_all_history(title="Hasil Trading Acak (Random Agent)")
    env.close()